### PR TITLE
Update dual_robot_startup.launch

### PR DESCRIPTION
**Pull request by ningquan-gu**
I modified the ports of the two robot. Otherwise, there will have an error: Failed to bind socket for port 50004 to address. Reason: Address already in use: Address already in use.
Beside, we shoud modify the custom port of alice external control into 60002

### CODE REVIEW

**Comment by Galanmon18** [comment]
I work in an environment with 2 UR robots and following the example of this repository I have the above problems. Making the changes in these requests has solved it and I have been able to test it in a real environment. I consider this is very useful and should be merged.

**Comment by fmauch** [comment]
Thank you @ningquan-gu for making this PR and thank you @Galanmon18 for bringing this up again.

**Review by fmauch — APPROVED** [review]
LGTM, thank you @ningquan-gu

**Comment by ningquan-gu** [comment]
> Thank you @ningquan-gu for making this PR and thank you @Galanmon18 for bringing this up again.

You're welcome!  It's my pleasure.

**Comment by ningquan-gu** [comment]
> I work in an environment with 2 UR robots and following the example of this repository I have the above problems. Making the changes in these requests has solved it and I have been able to test it in a real environment. I consider this is very useful and should be merged.

I am so glad to help you solve your problem. By the way, have you managed to control the dual-arm robot to move simultaneously successfully? I have tried numerous times, but I have failed. 
The question is here: https://github.com/UniversalRobots/Universal_Robots_ROS_Tutorials/issues/10
@Galanmon18

**Comment by ningquan-gu** [comment]
> LGTM, thank you @ningquan-gu

You're welcome! It's my pleasure. @fmauch

**Comment by Galanmon18** [comment]
> I am so glad to help you solve your problem. By the way, have you managed to control the dual-arm robot to move simultaneously successfully? I have tried numerous times, but I have failed. The question is here: #10 @Galanmon18

Unfortunately not yet @ningquan-gu . I am having the same problem as you. If I figure out how to do it I will tell you

**Comment by ruanjinchen** [comment]
@Galanmon18 Hello, can you control both arms now?

**Pull request merged**
